// subscription: data access.
//
// Defines the repository interface consumed by service.go plus its PostgreSQL
// implementation. Translates database rows to and from domain models.
//
// Contains NO business rules. SQL lives in backend/queries/ and is generated by sqlc into
// internal/database/sqlc.
//
// See ARCHITECTURE.md 9, 5.3, 10 (schema).

package subscription
